const NOTIFICATION_TYPES = {
  WELCOME: 'WELCOME',
  USER_LOGIN: 'USER.LOGIN',
  USER_UPDATE: 'USER.UPDATE',
  CARD_CREATE: 'CARD.CREATE',
  CARD_ACTIVATE: 'CARD.ACTIVATE',
  TRANSACTION_PURCHASE: 'TRANSACTION.PURCHASE',
  TRANSACTION_SAVE: 'TRANSACTION.SAVE',
  TRANSACTION_PAID: 'TRANSACTION.PAID',
  REPORT_ACTIVITY: 'REPORT.ACTIVITY'
};

const TABLE_NAMES = {
  NOTIFICATIONS: process.env.NOTIFICATION_TABLE_NAME || 'notification-table',
  NOTIFICATION_ERRORS: process.env.NOTIFICATION_ERROR_TABLE_NAME || 'notification-error-table'
};

const QUEUE_URLS = {
  NOTIFICATION_EMAIL: process.env.NOTIFICATION_EMAIL_SQS_URL,
  NOTIFICATION_ERROR: process.env.NOTIFICATION_EMAIL_ERROR_SQS_URL
};

const S3_BUCKETS = {
  EMAIL_TEMPLATES: process.env.EMAIL_TEMPLATES_BUCKET || 'templates-email-notification'
};

const EMAIL_CONFIG = {
  FROM_EMAIL: process.env.FROM_EMAIL || 'jesusdanielpalacioavila50@gmail.com',
  FROM_NAME: process.env.FROM_NAME || 'Inferno Bank'
};

const TEMPLATE_MAPPING = {
  [NOTIFICATION_TYPES.WELCOME]: 'welcome.html',
  [NOTIFICATION_TYPES.USER_LOGIN]: 'user-login.html',
  [NOTIFICATION_TYPES.USER_UPDATE]: 'user-update.html',
  [NOTIFICATION_TYPES.CARD_CREATE]: 'card-create.html',
  [NOTIFICATION_TYPES.CARD_ACTIVATE]: 'card-activate.html',
  [NOTIFICATION_TYPES.TRANSACTION_PURCHASE]: 'transaction-purchase.html',
  [NOTIFICATION_TYPES.TRANSACTION_SAVE]: 'transaction-save.html',
  [NOTIFICATION_TYPES.TRANSACTION_PAID]: 'transaction-paid.html',
  [NOTIFICATION_TYPES.REPORT_ACTIVITY]: 'report-activity.html'
};

module.exports = {
  NOTIFICATION_TYPES,
  TABLE_NAMES,
  QUEUE_URLS,
  S3_BUCKETS,
  EMAIL_CONFIG,
  TEMPLATE_MAPPING
};